### ISSUE TITLE
Version of transformers library

### ISSUE THREAD

**Issue by anhquan075** [anisha2102/docvqa#10]
Can I get more information about Transformers version? I get a lot of errors when running run_docvqa.py cause Transformers version is not matched with another library. Thank you so much

**Comment by anisha2102** [comment]
It's 2.8.0 for me. Hope that helps.

**Comment by anhquan075** [comment]
> It's 2.8.0 for me. Hope that helps.

I try with 2.5.1 and it works. Btw thank you so much
