### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by jmayank23** [anisha2102/docvqa#11]
I notice the code is in Tensorflow but the Google Drive link is a PyTorch model. Will there be a TF Model in the future?
Is the PyTorch model a trained model?

**Comment by jockeyyan** [comment]
It actually is a pytorch model and tensorflow only help to load data etc.

**Comment by jmayank23** [comment]
Got it, thank you for the quick reply

Is the pytorch model on Google Drive a trained one?

**Comment by anisha2102** [comment]
Yes, the drive link has the model trained on docvqa dataset.
