### ISSUE TITLE
Details of install requirements

### ISSUE THREAD

**Issue by MonsKim999** [anisha2102/docvqa#5]
Hi, 
Thank you for opening your code.
I want to know the details of the version about the install requirements.
There are some collisions between modules.

Could you provide me a list of 'conda list'?

Thank you.

**Comment by anisha2102** [comment]
Attaching the output of `pip list`. Hope this helps.

Package                  Version     
------------------------ ------------
numpy                    1.18.1
opencv-python            4.2.0.34
torch                    1.4.0
torchvision              0.5.0
tensorboardX             2.0
tensorflow-gpu           1.14.0

**Comment by MonsKim999** [comment]
@anisha2102

Thank you!
Could you let me know the version of apex?
There is a problem while loading a parallel model.

Did you install the apex by pip operand or directly clone the project?

Best,
JungjunKim.

**Comment by anisha2102** [comment]
@MonsKim999 

I installed apex by cloning the project. The version in my pip list is `apex 0.1`
Reference: [https://github.com/NVIDIA/apex](url)
Hope this helps to resolve your issue.

**Comment by MonsKim999** [comment]
@anisha2102

Thanks a lot :)
