### ISSUE TITLE
cannot find "test.txt"file

### ISSUE THREAD

**Issue by dongxuewang-123** [anisha2102/docvqa#6]
when I run run_docvqa.py:
with open(os.path.join(args.data_dir,"test.txt"),"r") as f:
cannot find this txt file,can you show me where can I find this file or how can I create this file ?

**Comment by anisha2102** [comment]
I am yet the update the testing scripts for unseen datasets on this repo. I believe you are getting that error as you have activated the _--do_predict_ flag in the code. Request you to rerun without the flag as it is not relevant to the functionality of training and evaluation processes.

**Comment by dongxuewang-123** [comment]
But if I want to test my model on test set,how should I do?
